name: Publish
on:
  push:
    tags:
      - "foo.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Get the tag
      id: get-tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Print the tag
      run: echo ${{ steps.get-tag.outputs.tag }}
    - name: Print the token
      run: echo ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub Release
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d "{ \"tag_name\": \"${{ steps.get-tag.outputs.tag }}\", \"name\": \"Release ${{ steps.get-tag.outputs.tag }}\" }" \
        https://api.github.com/repos/${{ github.repository }}/releases
    - name: Upload an asset to the GitHub Release
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/octet-stream" \
        https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get-tag.outputs.tag }}/assets?name=README.md \
        --data-binary "@README.md"
