name: Publish
on:
  push:
    tags:
      - "foo.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Get the tag
      id: get-tag
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Print the tag
      run: echo ${{ steps.get-tag.outputs.tag }}
    - name: Create a GitHub Release
      uses: "actions/github-script@v6"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          try {
            const response = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: false,
              name: 'Release ${{ steps.get-tag.outputs.tag }}',
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: '${{ steps.get-tag.outputs.tag }}',
            });

            core.exportVariable('RELEASE_ID', response.data.id);
            core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
          } catch (error) {
            core.setFailed(error.message);
          }
    - name: Print the RELEASE_ID
      run: echo "${{ env.RELEASE_ID }}"
    - name: Print the RELEASE_UPLOAD_URL
      run: echo "${{ env.RELEASE_UPLOAD_URL }}"
